# Rename this file to languages.toml to enable multilingual support
# [en]
# languageName = "English"
# languagedirection = "ltr"
# title = "Example Site"
# weight = 1


[zh]
languageName = "中文"
languagedirection = "ltr"
title = "中文"
weight = 1
