# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

# git 库
[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/CaiJemmy/CaiNiaoTool"

[social.params]
icon = "brand-github"

# [[social]]
# identifier = "twitter"
# name = "Twitter"
# url = "https://twitter.com"
# 
# [social.params]
# icon = "brand-twitter"
