# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/favicon.png"

[footer]
since = 2020
customText = "工欲善其事，必先利其器。"

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

################################################################################
# 左边侧栏显示
[sidebar]
# compact = true   # 默认false，头像和subtitle分行显示，true：头像和subtitle一行显示。
emoji = "🍥"
subtitle = "盛世之牛马，乱世之炮灰；平安榨其身，战时用其命。生如蝼蚁不敢有鸿鹄之志，命似纸薄岂能无青云之心。"

[sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png"
################################################################################

################################################################################
# 文章显示
[article]
headingAnchor = false
math = false               # 可以单独设置，参考快速入门中的例子
readingTime = true
# toc = true               # 目前没有发现界面上的变化

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"
################################################################################

################################################################################
## Widgets 小部件位于博客的右侧边栏。它们用于显示一些信息，例如：类别、标签等。
# 
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"
################################################################################

################################################################################
# 不支持 twitter
[opengraph.twitter]
site = ""
card = "summary_large_image"
################################################################################

################################################################################
#
#
#
[defaultImage.opengraph]
enabled = false
local = false
src = ""
################################################################################

################################################################################
# 
[colorScheme]
toggle = true
default = "dark"
################################################################################

################################################################################
[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true
################################################################################

################################################################################
## Comments 评论
# [comments]
# enabled = true
# provider = "disqus"
# 
# [comments.disqusjs]
# shortname = ""
# apiUrl = ""
# apiKey = ""
# admin = ""
# adminLabel = ""
# 
# [comments.utterances]
# repo = ""
# issueTerm = "pathname"
# label = ""
# 
# [comments.remark42]
# host = ""
# site = ""
# locale = ""
# 
# [comments.vssue]
# platform = ""
# owner = ""
# repo = ""
# clientId = ""
# clientSecret = ""
# autoCreateIssue = false
# 
# [comments.waline]
# serverURL = ""
# lang = ""
# visitor = ""
# avatar = ""
# emoji = ["https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo"]
# requiredMeta = ["name", "email", "url"]
# placeholder = ""
# 
# [comments.waline.locale]
# admin = "Admin"
# 
# [comments.twikoo]
# envId = ""
# region = ""
# path = ""
# lang = ""
# 
# [comments.cactus]
# defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
# serverName = "cactus.chat"
# siteName = ""
# 
# [comments.giscus]
# repo = ""
# repoID = ""
# category = ""
# categoryID = ""
# mapping = ""
# lightTheme = ""
# darkTheme = ""
# reactionsEnabled = 1
# emitMetadata = 0
# 
# [comments.gitalk]
# owner = ""
# admin = ""
# repo = ""
# clientID = ""
# clientSecret = ""
# 
# [comments.cusdis]
# host = ""
# id = ""
